version: '3.8'

services:

  db:
    container_name: postgres
    image: postgres
    command: -p ${POSTGRES_DB_PORT}
    expose:
      - ${POSTGRES_DB_PORT}
    restart: 'always'
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_USER}
      - POSTGRES_USER=${POSTGRES_DB_USER}
    volumes:
      - ./postgres:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: 'redis:latest'
    restart: 'always'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=${PORT_REDIS}
    ports:
      - '${PORT_REDIS}:6379'
    volumes:
      - '$PWD/redis.conf:/usr/local/etc/redis/redis.conf'
    command:
      - 'redis-server'
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]

  api:
    container_name: fast_api
    build:
      dockerfile: Dockerfile
    restart: 'always'
    env_file:
      - .env
    environment:
      - API_REDIS_HOST=redis
    ports:
      - '${FAST_API_PORT}:8000'
    depends_on:
      - db
      - redis
    entrypoint: ./start.sh